client/package-lock.json, client/package.json, client/src/App.jsx, client/src/Components/CommonComponent/Button/index.jsx, client/src/Components/CommonComponent/Button/style.css, client/src/Components/CommonComponent/Header/style.css
related to #94 
I made button component with style .
that Includes two file (index.jsx , style.css).
- - [x] You can download and install locally, and run the project locally
- - [x] All existing and new features run without bugs
- - [x] The build script runs without error
- - [x] Linter is used, no error messages
- - [x] Code is consistent with agreed team style
- - [x] Naming of files is consistent with project (e.g. all files named with camelCase)
- - [x] Console.log is only used for crucial system messages (e.g. which port server is on).
- - [x] Any console.logs used for debugging have been removed.
=> make button component

client/src/App.jsx
transfer the App from stateless to stateful.
=> make app from stateless to statefull

.gitignore, client/.eslintrc.json, server/controller/index.js, server/controller/middleware/authentication.js, server/controller/middleware/protectRoute.js
related to #118 
create two middleware:
- authentication: for check the cookie.
- protectRoute: to check if the request has the correct payload or not to protect the protected route.
=> Middleware

server/database/config/dbBuild.sql, server/database/config/dbFake.sql
make a new table for a relation between orders and TUser.
=> Fix database

client/src/App.jsx, client/src/Components/Layouts/Login/index.jsx, client/src/Components/Layouts/Login/style.css
related to #125 
- make modifications on width and height and another style for login style.
- modify the class name of some elements.
- handle the response in fetch
=> Login page refactor

server/controller/accountsMangment/admin/checkLogin.js, server/controller/accountsMangment/admin/index.js, server/controller/index.js, server/controller/middleware/authentication.js, server/controller/middleware/protectRoute.js, server/database/queries/admin/checkAdmin.js
related to #41
- create an admin folder in the controller
- make check for username and password in checkAdmin
- add it in the controller index.
- modify the variable name of protecting and check middleware.
=> Login route backend

server/controller/index.js, server/controller/order/deleteOrder.js, server/controller/order/index.js, server/database/config/dbBuild.sql, server/database/queries/order/deleteOrder.js
related to #66 
- create a query to delete specific orders.
-  create a route for `deleteOrder/:id`
- create a module to delete the order.
=> Delete order backend

client/src/Components/Layouts/Captains/Popups/AddCaptain.jsx, client/src/Components/Layouts/Captains/style.css
related to #54 
- modify the class name of the front end
=> Fix style popup add captain

server/controller/index.js, server/controller/place/getPlacesNames.js, server/controller/place/index.js, server/database/queries/place/getPlaceName.js
related to #84 
- create a query for getting places names and their id.
- create `/getPlacesNames` route.
- create a module to send places names and id.
=> Get places names

server/controller/accountsMangment/captains/getCaptaisnNames.js, server/controller/accountsMangment/captains/index.js, server/controller/index.js, server/database/queries/captain/getCaptainName.js
related to #86 
- create a query for getting captains names and their id.
- create `/getCaptainsNames` route.
- create a module to send captains names and id.
=> Get captain name

client/src/Components/CommonComponent/Table/Table.jsx, client/src/Components/Layouts/SingleCustomer/index.jsx
=> Delete order front

client/src/Components/Layouts/Order/addOrder.jsx, server/controller/index.js, server/controller/order/index.js, server/controller/order/postOrder.js, server/database/queries/captain/insertTuserOrder.js, server/database/queries/item/insertItem.js, server/database/queries/order/addOrder.js
=> Add order backend

client/package-lock.json, client/src/App.jsx, client/src/Components/CommonComponent/Navbar/index.jsx, client/src/Components/CommonComponent/Navbar/style.css, client/src/Components/CommonComponent/Sidebar/index.jsx, client/src/Components/HOC/WithNavSide.jsx, client/src/Components/Layouts/Captains/index.jsx, client/src/Components/Layouts/Customers/index.jsx, client/src/Components/Layouts/Home/index.jsx, client/src/Components/Layouts/NotFound/index.jsx, client/src/Components/Layouts/Ordersmanagement/index.jsx, client/src/Components/Layouts/SingleCaptains/index.jsx, client/src/Components/Layouts/SingleCustomer/index.jsx, client/src/Components/Layouts/ToBuildLater/index.jsx, client/src/Components/Layouts/ToBuildLater/style.css, server/controller/accountsMangment/admin/getName.js, server/controller/accountsMangment/admin/index.js, server/controller/accountsMangment/admin/logout.js, server/controller/index.js
=> api of all  routes front end

client/src/App.jsx, client/src/Components/CommonComponent/Table/Table.jsx, client/src/Components/Layouts/Captains/index.jsx, client/src/Components/Layouts/Captains/style.css, client/src/Components/Layouts/SingleCaptains/index.jsx, package-lock.json, server/controller/accountsMangment/captains/getCaptains.js, server/controller/accountsMangment/captains/index.js, server/database/queries/captain/getCaptains.js
=> Captain managment

server/controller/getImage.js, server/database/config/dbFake.sql, server/database/queries/captain/getCaptainName.js
- modify the image extension
- modify the query of getting the name of the captain
- add more captain in fake data
=> Modify backend image captain

server/controller/accountsMangment/captains/index.js
=> add deletecaptain route in index captain

client/src/Components/Layouts/Captains/style.css
- edit the style of add captain popup
- edit the select item
- edit the name of the file when uploading it
=> edit the style of popup

client/src/Components/Layouts/SingleCaptains/Popups/viewPopUp.jsx
=> fix the error in name of customer

server/controller/order/postOrder.js, server/database/queries/item/insertItemOrder.js
=> Fix add order

client/src/Components/Layouts/Login/index.jsx
Relates #187 
- add a form for the login page and submit
=> Fix login page

client/src/Components/Layouts/SingleCaptains/Popups/viewPopUp.jsx, client/src/Components/Layouts/SingleCaptains/style.css, client/src/Components/Layouts/SingleCustomer/Popups/viewPopUp.jsx
=> View order fexed style

client/src/Components/CommonComponent/Table/Popups.jsx, client/src/Components/CommonComponent/Table/Table.jsx
change the structure and style of view popup of captain.
=> Fix style view captian

client/src/Components/Layouts/Captains/style.css, client/src/Components/Layouts/Customers/index.jsx, server/controller/utils/addCustomerSchema.js
=> back validation for add customer 

server/controller/accountsMangment/customer/addCustomer.js
=> add validation schema to customer index

client/src/Components/Layouts/Order/addOrder.jsx, server/controller/utils/addCaptainSchema.js, server/controller/utils/addOrderValadation.js
=> Refactor add order

client/src/Components/Layouts/Customers/editcustomer.jsx, server/controller/accountsMangment/customer/editCustomer.js, server/controller/utils/editCustomerSchema.js
#186 
add validation for edit customer with to state 
1- schema if there a new password for the customer.
2- schema if there isn't a new password for the customer.
=> Edit customer validation

client/src/Components/CommonComponent/Table/Table.jsx, client/src/Components/CommonComponent/Table/dropdownMenu.jsx
related to #151 
- fix the dropdown
=> Refactor dropdown

client/package-lock.json, package-lock.json
=> install pakages
